

MODEL_PATH: './model'
CONST_FONT_STYLE: './font/msyh.ttf"'
KNOWN_FACE: './known_face'
RECORD_SAVE_PATH: './video'
PHOTO_SAVE_PATH: './photo'

EMAIL_CFG:
  smtp_host: 'smtp.sina.com'
  smtp_port: 25
  smtp_timeout: 30.0
  smtp_login: 'ghostwwl@sina.com'
  smtp_password: 'sina×××××××'

FAMILY_MEMBERS:
  '吴乐':
    'wechat': 'https://sc.ftqq.com/SCU38351T8f9d11ed939b6d976e0781465c259e468313b.send?{0}' # 自己去申请
    'email': 'ghostwwl@139.com'

